# Welcome to Jekyll!
# ...

# Site settings
title: ""
email: odwyerbeth621@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
minimal_mistakes_skin: default
search: true

header:
  title: ""
  image: "/assets/images/Colorful Pastel Modern Personal LinkedIn Banner (1584 x 200 px).png"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: "America/New_York"

include:
  - _pages

# Exclude from processing.
# ...

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Beth O'Dwyer"
  avatar: "/assets/images/logo.png"
  bio: ""
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/elodwyer1"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/elodwyer/"
    - label: "odwyerbeth621@gmail.com"
      icon: "fa-solid fa-envelope"
      url: "mailto:odwyerbeth621@gmail.com"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/elodwyer1"
    - label: "LinkedIn"
      icon: "fa-brands fa-linkedin"
      url: "https://www.linkedin.com/in/elodwyer/"

defaults:
  - scope:
      path: "projects"
      type: projects
    values:
      layout: single
      author_profile: false
      share: true
  - scope:
      path: "certificates"
      type: certificates
    values:
      layout: single
      author_profile: false
      share: true
  - scope:
      path: "posts"
      type: posts
    values:
      layout: posts
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

collections:
  projects:
    output: true
    permalink: /projects/:path/
#certificates collection
  certificates:
    output: true
    permalink: /certificates/:path/

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/
